import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import { runDashScopeSpeechRound } from "./dashscopeClient.js";
import { characterErrorRate, hashFixtureManifest, summarizeObservations } from "./metrics.js";
import { networkProfiles } from "./network.js";
import { speechBenchmarkSamples, validateSpeechBenchmarkSamples } from "./sampleManifest.js";
import { loadDashScopeExperimentConfig, sanitizeDiagnostic } from "./safety.js";
import type { SpeechBenchmarkReport, UploadMode } from "./types.js";

function readArgument(name: string): string | undefined {
  const index = process.argv.indexOf(name);
  return index === -1 ? undefined : process.argv[index + 1];
}

async function main(): Promise<void> {
  validateSpeechBenchmarkSamples(speechBenchmarkSamples);
  const fixturesDir = readArgument("--fixtures-dir");
  const reportPath = readArgument("--report");
  const profileId = readArgument("--network") ?? "wifi_good";
  const uploadMode = (readArgument("--upload-mode") ?? "buffer_on_commit") as UploadMode;
  const profile = networkProfiles.find((candidate) => candidate.id === profileId);

  if (!fixturesDir || !reportPath) {
    throw new Error("Usage: --fixtures-dir <private WAV directory> --report <sanitized JSON path>");
  }
  if (!profile) {
    throw new Error(`Unknown network profile: ${profileId}`);
  }
  if (uploadMode !== "buffer_on_commit" && uploadMode !== "upstream_streaming") {
    throw new Error(`Unknown upload mode: ${uploadMode}`);
  }

  const config = loadDashScopeExperimentConfig();
  const observations = [];
  for (const sample of speechBenchmarkSamples) {
    const observation = await runDashScopeSpeechRound({
      sample,
      fixturePath: path.join(fixturesDir, sample.audioFile),
      ...config,
      networkProfile: profile,
      uploadMode,
    });
    if (observation.status === "succeeded" && observation.transcript) {
      observation.characterErrorRate = characterErrorRate(
        sample.expectedText,
        observation.transcript,
      );
    }
    observations.push(observation);
  }

  const report: SpeechBenchmarkReport = {
    schemaVersion: 1,
    generatedAt: new Date().toISOString(),
    fixtureManifestHash: hashFixtureManifest(speechBenchmarkSamples),
    providerEvidence: observations.every((observation) => observation.status === "succeeded")
      ? "complete"
      : observations.some((observation) => observation.status === "succeeded")
        ? "partial"
        : "none",
    observations,
    summary: summarizeObservations(observations),
    limitations: [
      "Fixtures are stored outside the repository and must not contain real traveler PII.",
      "Network impairment is generated by the client harness, not by a carrier or venue router.",
      "This experimental report does not freeze a production provider or device protocol.",
    ],
  };

  await mkdir(path.dirname(reportPath), { recursive: true });
  await writeFile(reportPath, `${JSON.stringify(report, null, 2)}\n`, { mode: 0o600 });
  process.stdout.write(
    `${JSON.stringify({ ok: true, report: reportPath, summary: report.summary })}\n`,
  );
}

main().catch((error) => {
  process.stderr.write(`${JSON.stringify({ ok: false, error: sanitizeDiagnostic(error) })}\n`);
  process.exitCode = 1;
});
