import {
  GenerationProgressSchema,
  applyPatch,
  type GenerationProgress,
  type TripBlock,
  type TripDay,
} from "@visepanda/domain";
import { z } from "zod";
import type { TripService } from "../trip/service.js";

export const CompleteTripInputSchema = z.object({
  tripId: z.string().min(1),
  maxAttemptsPerDay: z.number().int().positive().default(2),
});

export type CompleteTripInput = z.input<typeof CompleteTripInputSchema>;

type CompleteDay = (day: TripDay) => Promise<TripBlock>;

export function createTwoPassWorker({
  tripService,
  completeDay = defaultCompleteDay,
}: {
  tripService: TripService;
  completeDay?: CompleteDay;
}) {
  return {
    async completeTrip(input: CompleteTripInput): Promise<GenerationProgress> {
      const parsed = CompleteTripInputSchema.parse(input);
      const trip = await tripService.get(parsed.tripId);
      if (!trip) throw new Error(`Trip not found: ${parsed.tripId}`);

      let nextTrip = trip;
      const emptyDays = trip.days.filter((day) => day.blocks.length === 0);
      let progress = GenerationProgressSchema.parse({
        status: emptyDays.length === 0 ? "completed" : "completing",
        totalDays: emptyDays.length,
      });

      for (const day of emptyDays) {
        let lastError: unknown;

        for (let attempt = 1; attempt <= parsed.maxAttemptsPerDay; attempt += 1) {
          progress = { ...progress, attempts: progress.attempts + 1 };

          try {
            const block = await completeDay(day);
            nextTrip = applyPatch(nextTrip, {
              operations: [{ op: "upsert_block", dayId: day.id, block }],
            });
            progress = { ...progress, completedDays: progress.completedDays + 1 };
            break;
          } catch (error) {
            lastError = error;
            if (attempt === parsed.maxAttemptsPerDay) {
              return GenerationProgressSchema.parse({
                ...progress,
                status: "failed",
                error: error instanceof Error ? error.message : String(lastError),
              });
            }
          }
        }
      }

      await tripService.save(nextTrip);
      return GenerationProgressSchema.parse({ ...progress, status: "completed" });
    },
  };
}

function defaultCompleteDay(day: TripDay): Promise<TripBlock> {
  return Promise.resolve({
    id: `auto-${day.id}`,
    type: "free_time",
    title: day.title ? `${day.title} details` : `Day ${day.dayNumber} details`,
    description: "Generated by the second pass worker.",
    status: "planned",
  });
}
